import { UserRole } from '../../../common/enums/user-role.enum';
import type { AuthPermission } from '../auth.constants';

const OFFICER_PERMISSIONS: AuthPermission[] = [
  'profile:read:self',
  'profile:update:self',
  'organisation:read:self',
  'officer:read:self',
  'device:read:self',
  'shift:read:self',
  'assignment:read:self',
  'assignment:confirm:self',
  'attendance:clock-in:self',
  'attendance:clock-out:self',
  'attendance:create:self',
  'attendance:read:self',
  'break:start:self',
  'break:end:self',
  'break:read:self',
  'patrol-route:read',
  'patrol-checkpoint:read',
  'patrol-assignment:read:self',
  'patrol-visit:create:self',
  'patrol-visit:read:self',
  'incident:create:self',
  'incident:read:self',
  'evidence:upload:self',
  'evidence:read:self',
  'patrol:read:self',
  'patrol:complete:self',
  'notification:read:self',
  'notification:update:self',
  'device:push-token:self',
  'sos:create:self',
  'support:create:self',
  'support:read:self',
  'sync:submit:self',
];

const SUPERVISOR_PERMISSIONS: AuthPermission[] = [
  ...OFFICER_PERMISSIONS,
  'officer:read',
  'officer:read:assigned',
  'supervisor:read',
  'client:read',
  'site:read',
  'shift:read',
  'assignment:read',
  'attendance:read',
  'attendance:read:assigned',
  'attendance:review',
  'attendance:approve',
  'break:read',
  'break:review',
  'patrol-route:read',
  'patrol-checkpoint:read',
  'patrol-assignment:read',
  'patrol-assignment:review',
  'patrol-visit:read',
  'patrol-visit:review',
  'incident:read:assigned',
  'incident:read',
  'incident:update',
  'incident:acknowledge',
  'incident:dispatch',
  'incident:assign',
  'incident:close',
  'incident:reopen',
  'incident:escalate',
  'incident:note',
  'evidence:read',
  'evidence:verify',
  'evidence:delete',
  'emergency:read',
  'emergency:manage',
  'support:read',
  'support:update',
  'report:read',
  'patrol:monitor',
  'sos:respond',
];

const PHASE7_ADMIN_PERMISSIONS: AuthPermission[] = [
  'incident:read',
  'incident:assign',
  'incident:close',
  'incident:reopen',
  'incident:escalate',
  'incident:note',
  'incident:manage',
  'evidence:read',
  'evidence:verify',
  'evidence:delete',
  'evidence:manage',
  'notification:broadcast',
  'notification:manage',
  'emergency:read',
  'emergency:manage',
  'support:read',
  'support:update',
  'support:manage',
  'faq:manage',
  'sync:manage',
  'report:read',
];

const PHASE4_ADMIN_PERMISSIONS: AuthPermission[] = [
  'organisation:read:self',
  'organisation:update:self',
  'user:create',
  'user:read',
  'user:update',
  'user:disable',
  'user:archive',
  'user:unlock',
  'user:reset-password',
  'user:manage-role',
  'user:manage',
  'officer:create',
  'officer:read',
  'officer:update',
  'officer:archive',
  'officer:manage',
  'supervisor:create',
  'supervisor:read',
  'supervisor:update',
  'supervisor:archive',
  'supervisor:assign-officer',
  'client:create',
  'client:read',
  'client:update',
  'client:archive',
  'client:manage',
  'site:create',
  'site:read',
  'site:update',
  'site:archive',
  'site:manage',
  'device:read',
  'device:approve',
  'device:revoke',
  'device:block',
  'device:unblock',
];

const PHASE5_ADMIN_PERMISSIONS: AuthPermission[] = [
  'shift:create',
  'shift:read',
  'shift:update',
  'shift:cancel',
  'shift:archive',
  'shift:manage',
  'assignment:create',
  'assignment:read',
  'assignment:update',
  'assignment:cancel',
  'assignment:reassign',
  'assignment:manage',
  'attendance:read',
  'attendance:review',
  'attendance:approve',
  'attendance:correct',
  'attendance:void',
  'break:read',
  'break:review',
];

const PHASE6_ADMIN_PERMISSIONS: AuthPermission[] = [
  'patrol-route:create',
  'patrol-route:read',
  'patrol-route:update',
  'patrol-route:activate',
  'patrol-route:archive',
  'patrol-checkpoint:create',
  'patrol-checkpoint:read',
  'patrol-checkpoint:update',
  'patrol-checkpoint:reorder',
  'patrol-checkpoint:archive',
  'patrol-assignment:create',
  'patrol-assignment:read',
  'patrol-assignment:update',
  'patrol-assignment:cancel',
  'patrol-assignment:review',
  'patrol-visit:read',
  'patrol-visit:review',
  'patrol-visit:override',
];

const ADMINISTRATOR_PERMISSIONS: AuthPermission[] = [
  ...SUPERVISOR_PERMISSIONS,
  ...PHASE4_ADMIN_PERMISSIONS,
  ...PHASE5_ADMIN_PERMISSIONS,
  ...PHASE6_ADMIN_PERMISSIONS,
  ...PHASE7_ADMIN_PERMISSIONS,
  'report:read',
  'audit:read',
];

/** Platform-only; does not inherit unrestricted tenant management. */
const SUPER_ADMIN_PERMISSIONS: AuthPermission[] = [
  'platform:manage',
  'admin:system:read',
  'admin:system:manage',
  'organisation:read:any',
  'organisation:update:any',
  'organisation:suspend:any',
  'audit:read',
];

const ROLE_PERMISSIONS: Record<UserRole, AuthPermission[]> = {
  [UserRole.SECURITY_OFFICER]: OFFICER_PERMISSIONS,
  [UserRole.SUPERVISOR]: SUPERVISOR_PERMISSIONS,
  [UserRole.ADMINISTRATOR]: ADMINISTRATOR_PERMISSIONS,
  [UserRole.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,
};

export function getPermissionsForRole(role: UserRole): AuthPermission[] {
  return [...ROLE_PERMISSIONS[role]];
}

export function roleHasPermission(role: UserRole, permission: string): boolean {
  return ROLE_PERMISSIONS[role].includes(permission as AuthPermission);
}
